apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: podinfo-gateway
  namespace: demo
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 9898
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: demo
spec:
  hosts:
    - "*"
  gateways:
    - podinfo-gateway.demo.svc.cluster.local
  http:
    route:
      - destination:
          host: podinfo.demo.svc.cluster.local
